spring:
  application:
    name: redisplayground
  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      timeout: 3000
      jedis:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2
          max-wait: 2000